services:
    postgres:
        image: postgres:16-alpine
        restart: on-failure
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-example_shop_database}
            POSTGRES_USER: ${POSTGRES_USER:-user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
        volumes:
            - './docker/postgres/data:/var/lib/postgresql/data'

    nginx:
        image: nginx:1.27-alpine
        restart: on-failure
        depends_on:
            - php
        volumes:
            - './api:/api'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '80:80'

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        volumes:
            - './api:/api'
            - './docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini'
        depends_on:
            - postgres

    redis:
        image: redis:7.4-alpine
        ports:
            - '6379:6379'